apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeRouter
metadata:
  name: name # {"$kpt-set":"name"}
spec:
  description: Router to allow outbound internet access
  region: REGION # {"$kpt-set":"gcloud.compute.region"}
  networkRef:
    external: "" # {"kpt-set":"network-ref-external"}
    name: name # {"$kpt-set":"network-ref-name"}
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeRouterNAT
metadata:
  name: name # {"$kpt-set":"name"}
spec:
  region: REGION # {"$kpt-set":"gcloud.compute.region"}
  routerRef:
    external: "" # {"$kpt-set":"router-ref-external"}
    name: name # {"$kpt-set":"router-ref-name"}
  natIpAllocateOption: AUTO_ONLY
  sourceSubnetworkIpRangesToNat: ALL_SUBNETWORKS_ALL_IP_RANGES
